FROM node:20

RUN apt-get update && apt-get install -y \
    gosu

RUN corepack enable

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

COPY . .

EXPOSE 4200

CMD ["yarn", "start"]