services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://symfony:secret@db:5432/symfony
      UID: "${UID}"
      GID: "${GID}"
    depends_on:
      - db
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "composer install && php bin/console doctrine:migrations:migrate --no-interaction && symfony server:start --listen-ip=0.0.0.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    user: "${UID}:${GID}" # If an anonymous node_modules volume is created, this will cause a file ownership issue.
    environment:
      UID: "${UID}"
      GID: "${GID}"
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    #  - /app/node_modules # Meant to provide environment portability, but disabled to work around an IDE configuration problem.
    command: sh -c "yarn install && yarn start"

volumes:
  db-data:
