FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    wget \
    git zip unzip libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

WORKDIR /app

RUN wget https://get.symfony.com/cli/installer -O - | bash && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

COPY . /app

RUN composer install

EXPOSE 8000